from datetime import datetime
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


INVOICE_DIR = Path("media/invoices")
INVOICE_DIR.mkdir(parents=True, exist_ok=True)


def generate_invoice(
    username: str,
    plan_name: str,
    price: int,
    start_date: datetime,
    end_date: datetime,
    transaction_id: str
) -> str:

    filename = f"invoice_{transaction_id}.pdf"
    file_path = INVOICE_DIR / filename

    pdf = canvas.Canvas(str(file_path), pagesize=A4)

    width, height = A4

    # Header
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(50, height - 60, "Blog Management API")

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, height - 100, "Subscription Invoice")

    # Invoice details
    pdf.setFont("Helvetica", 11)

    y = height - 150

    details = [
        ("User Name", username),
        ("Plan Name", plan_name),
        ("Price", f"Rs. {price}"),
        ("Start Date", start_date.strftime("%Y-%m-%d %H:%M:%S")),
        ("End Date", end_date.strftime("%Y-%m-%d %H:%M:%S")),
        ("Transaction ID", transaction_id),
    ]

    for label, value in details:
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(50, y, f"{label}:")

        pdf.setFont("Helvetica", 11)
        pdf.drawString(180, y, str(value))

        y -= 30

    # Payment status
    y -= 10

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "Payment Status:")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(180, y, "Paid")

    # Footer
    pdf.setFont("Helvetica", 9)
    pdf.drawString(
        50,
        50,
        "This is a sample invoice generated by the Blog Management System."
    )

    pdf.save()

    # Store relative path in database
    return f"/media/invoices/{filename}"